version: '2'

services:
  web:
    restart: always
    build: .
    command: ./run_web.sh
    volumes:
      - ".:/home/django-channels"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: .env

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"

volumes:
  pg-data: {}
  redis-data: {}